language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t arcik888/docker-react -f Dockerfile.dev .

script: 
  - docker run -e CI=true arcik888/docker-react npm run test